Add type-definition
janis-commerce/event-listener pull request #3
Opened 2021-11-29 13:28 UTC by moruezabal

**Requerimiento:**
Se requiere agreagar estos TypeDef al package de Event-Listener

**Historia de usuario**
https://fizzmod.atlassian.net/browse/JCN-332

**Subtarea**
https://fizzmod.atlassian.net/browse/JCN-342

2021-12-02 12:41 UTC, gastonpereyra commented on lib/event-listener-error.js
>  class EventListenerError extends Error {
:exclamation: Cómo comente en el package de API-Get estos package quedaron viejitos y estaria bueno que se exporten las clases directamente

```js
module.exports = class EventListenerError extends Error {
```

2021-12-02 12:47 UTC, gastonpereyra requested changes
Deje comentarios simples

2021-12-06 13:35 UTC, gastonpereyra approved these changes

2021-12-13 12:37 UTC, juanhapes commented on lib/event-listener.js
> + * @typedef {Object} EventListenerError An instance of EventListenerError class
`EventListenerError`? 🤔

2021-12-13 12:48 UTC, juanhapes approved these changes

2021-12-13 13:00 UTC, merged